export const CHANGE_SEARCH = 'CHANGE_SEARCH'
export const ADD_MARKDOWNFILES = 'ADD_MARKDOWNFILES'
export const ADD_RESULT_FILTERED = 'ADD_RESULT_FILTERED '
export const EMPTY_RESULT_FILTER = 'EMPTY_RESULT_FILTERED '